### ISSUE TITLE
Possibility to disable all tests (set to default variants) by one cookie

### ISSUE THREAD

**Issue by Strajk** [VladimirJarabica/splitster#11]
That
would
be
•G•R•E•A•T•

**Comment by VladimirJarabica** [comment]
Hello Strajk.
Splitster is not really disabling it's test "by cookies".
He gets predefined value in it's initialization, so the only thing you should do (ok I'll do it in our code 😓 ) is:
Pass disabled in all predefined values, if you have received some cookies which you consider "disabling all test".
