### ISSUE TITLE
0.0.45 is to "chatty"

### ISSUE THREAD

**Issue by Strajk** [VladimirJarabica/splitster#13]
https://github.com/VladimirJarabica/splitster/blob/9e5c7aedf209a0001fa9c8fae74ae095d8422195/src/records/test/utils/setWinningVariant.js#L48

![image](https://user-images.githubusercontent.com/697301/53884791-a69bc880-401c-11e9-91cb-0672be146890.png)

**Comment by VladimirJarabica** [comment]
Solved in 0.0.46

**Comment by Strajk** [comment]
@VladimirJarabica 
![image](https://user-images.githubusercontent.com/697301/53974360-b55cab00-4102-11e9-88ba-07178a272bbf.png)
